### ISSUE TITLE
Will it be possible to edit the objects specified in "external quests"?

### ISSUE THREAD

**Issue by deevroman** [Helium314/StreetComplete#362]
At least the simplest tags editing🙏

**Comment by Helium314** [comment]
I had thought about this, but wanted to test how the external quest works out before investing more time.

I'll have a look at how much effort editing tags is and probably try implementing it within the next few weeks or so.

**Comment by Helium314** [comment]
Done. The "show tags" other answer is changed to allow editing (for all quests).
