### ISSUE TITLE
Make the description of the edit package less alarming

### ISSUE THREAD

**Issue by deevroman** [Helium314/StreetComplete#364]
*This should never be uploaded*

The description of the package of edits when manually editing tags looks alarming for other mappers.:)

<img width="322" alt="Снимок экрана 2022-04-12 в 00 22 08" src="https://user-images.githubusercontent.com/25708359/162835691-ac732716-9b86-4397-acf8-90da137f0b9f.png">

**Comment by Helium314** [comment]
The message actually depends on the quest, not on whether the "edit tags" answer has been used.
I had set this message as a warning for all quests where there is no option that makes changes. But of course with "edit tags", there is always the possibility of changing things.
Will be fixed soon.

**Comment by Helium314** [comment]
Fixed.
Will create a new release once upstream v43 beta is released.
