### ISSUE TITLE
Rename app launcher

### ISSUE THREAD

**Issue by amenk** [Helium314/StreetComplete#368]
Nice fork :-)

I installed https://github.com/Helium314/StreetComplete/releases/download/v43.0-beta1/app-release_43.0.apk
and it shows the same app icon and name and so is hard to distinguish from the official app.

Can we rename it to "Mod StreetComplete" or something like that?

**Comment by amenk** [comment]
Workaround: just put them on different positions of the home screen :-)

**Comment by Helium314** [comment]
> Workaround: just put them on different positions of the home screen :-)

That's how I do it as I never bothered looking up how to change the name
