### ISSUE TITLE
quick-hide button is covert by the on-screen navigation buttons

### ISSUE THREAD

**Issue by tiptoptom** [Helium314/StreetComplete#371]
This is weird... the button is basically a copy of the **ok** button, so the problem should also occur for the ok button, but apparently doesn't.
Differences:
1. hide button is smaller
2. hide button is aligned to *start* instead of *end* (i.e. left instead of right)
3. ok button is invisible in the beginning, while hide button isn't
4. hide button is (unnecessarily) set to become visible once quest fragment is created, while ok button becomes visible later

My best guess is that the problem is *3*: the button might be created before some navigation bar checks are done.
So I'll set it to be invisible at the start and you can tell me whether it helps.

_Originally posted by @Helium314 in https://github.com/Helium314/StreetComplete/issues/367#issuecomment-1121944740_

**Comment by tiptoptom** [comment]
I opened a new issue so as not to digress further on the other one.

The position of the quick-hide button in the version 43.1 works well for me.

**Comment by Helium314** [comment]
If this still happening in the latest version I have not idea what is going on, sorry...

**Comment by mnalis** [comment]
@tiptoptom also note there is currently small problem with version display (https://github.com/Helium314/StreetComplete/issues/374) so it might be confusion about which version is working for you and which isn't. 

It would be great if you could two versions (one working correctly, on incorrectly) of pciture (taken with another mobile if screenshot does not show problem?) accompanied by URL of web page from where you downloaded that version (as the version number alone is ambiguous currently as noted above)

**Comment by mnalis** [comment]
It seems to work fine on my Android 10 (Huawei P30pro) in new [43.0 draft (0c48ac2)](https://github.com/Helium314/StreetComplete/releases/tag/v43.0):
![small_Screenshot_20220530_223233_de westnordost streetcomplete modified](https://user-images.githubusercontent.com/156656/171059917-fb76c0b0-3802-4631-ad28-b5ebd5b39caa.jpg)


Can you try if that one works for you @tiptoptom ?

**Comment by tiptoptom** [comment]
Yes, it works for me. 👍
Thank you 🙏
