### ISSUE TITLE
Creating new empty profile instead creates a copy of default profile

### ISSUE THREAD

**Issue by mnalis** [Helium314/StreetComplete#372]
When creating a new profile, choosing to create `EMPTY PROFILE` should create profile with no quests selected. Instead, newly create profile has 128/162 quests enabled.

**How to Reproduce**

- go to `Manage profiles`
- click `+` to create a new profile
- choose `EMPTY PROFILE` from bottom right
- type the name of the profile, confirm and select it
- notice that the newly create profile is **not** empty 

**Versions affected**
H3 fork from [app-release_43.2.apk](https://github.com/Helium314/StreetComplete/issues/374) - which for some reason identifies itself as `v43.1` in `About` window, which is probably another bug (also, clicking on `Version history` in `About`, shows changelog for `v43.2` and `v44.0` too, and seems to contain `v44` features like GPX track recording)

**Comment by Helium314** [comment]
I had used the word *empty* to clarify the internal state. It is meant to make clear that the profile contains no data: quest visibility and order are empty, which means default visibility and order.

However, it does *not* create a copy of the *Default* profile (unless the *Default* profile is untouched, then you might see it as a copy).

**Comment by mnalis** [comment]
Ah, yes, that meaning of `empty` (for someone not knowing internals of SC) was quite confusing.
 
`DON'T COPY` as in new [43.0 draft (0c48ac2)](https://github.com/Helium314/StreetComplete/releases/tag/v43.0) seems to be much more understandable to me.

**Comment by Helium314** [comment]
< DON'T COPY as in new [43.0 draft (0c48ac2)](https://github.com/Helium314/StreetComplete/releases/tag/v43.0) seems to be much more understandable to me.

Yes, that's the reason why I changed the text
