### ISSUE TITLE
Add preference to "ask more quests"

### ISSUE THREAD

**Issue by mnalis** [Helium314/StreetComplete#375]
**Use case**

Many of [changes in my fork](https://github.com/mnalis/StreetComplete/blob/mnalis-everything/CHANGES-mnalis.md) are basically relaxing the quest selection query to return more quests than it would usually do.

**Proposed Solution**
Adding a global preference like `ask_more_quests`=`true`/`false`, which can easily be queried in each quest, would allow for easy implementation of those quests. It would also allow users easy switching between more/less quests (e.g. they might want to enable it only where they are in already-well-surveyed area)

(Possible alternative might be adding per-quest preference checkbox for that, but those seem to be global in current H3 fork, and would need to be per-preset instead, so user could duplicate preset and change only those. But while more powerful it seems like it would be making managing presets much harder - and it is hard enough already, so this is probably not a good alternative).

**Comment by Helium314** [comment]
I'd need some idea how to best approach this... Currently it will have issues very similar to quest settings:
* element selection is created on first scan for quests, and does not change until app is restarted
* already created quests are not affected by changes in element selection

I would prefer doing this via quest settings. In some quests the user can already adjust element selection according to preferences, and this is more flexible (for some quests I actually prefer asking for *fewer* elements).

Currently quest settings are global, but it could be coupled to profile/preset.

**Comment by mnalis** [comment]
yeah, "app restart + quest rescan is needed" is a problem.

Does that requirement go away when boolean preference "show more quests" is per-preset?
Or would one still need to manually scan for quests (or even restart app) after changing settings for display to update?

> Currently quest settings are global, but it could be coupled to profile/preset.

per-quest boolean flag (that is local to preset) would also work for me (as noted [above](https://github.com/Helium314/StreetComplete/issues/375#issue-1251618973)), but that would put `configure` button on much more quests. Which does sound bad from UI point of view, but then again, it gives users even more flexibility which is kind of point of this "expert" edition, so it might be good solution for the issue.

**Comment by Helium314** [comment]
> Does that requirement go away when boolean preference "show more quests" is per-preset?

The *rescan needed* will not go away. What could be done is deleting all quests and scan again automatically, without re-downloading OSM data. But this will be hideously slow, especially when it happens frequently, like on changing the profile.

I'm trying to find a way to avoid need for manual restart, but currently my ideas would either simply be automatic restart if possible, or require the element filter to be created from the filter string for every quest scan (instead of once). The latter should work, but I fear it wil have a really bad effect on performance.

> per-quest boolean flag (that is local to preset) would also work for me (as noted [above](https://github.com/Helium314/StreetComplete/issues/375#issue-1251618973)), but that would put `configure` button on much more quests. Which does sound bad from UI point of view, but then again, it gives users even more flexibility which is kind of point of this "expert" edition, so it might be good solution for the issue.

Here I'm definitely for more flexibility, as "ideal" element selection is often regional.
However, it's possible to add further pre-defined element selection choices to quest settings.

**Comment by Helium314** [comment]
I made the quest settings to optionally be pre-preset.
For restarting the app I found a way that works surprisingly well (like switching theme), you can test it with the new import function (added today) and importing settings. For Android 10 and above I read that the app might not restart, but don't have a device for testing.

I plan to add this restart to happen automatically when adjusting quest settings and going back to main settings screen.
But this does not cover switching profiles using the quick settings. This will need some testing...

**Comment by Helium314** [comment]
So restart now works more or less: if quest settings are changed, or the profiles is changed in settings and per-preset quest settings are switched on, the app will restart on re-entering the settings screen.
Unfortunately I didn't find a way to keep at settings screen, so the user is returned to map upon restart. Best I could do is warn the user that this will happen.

When changing profile using quick settings and per-preset quest settings are enabled, there is a warning, but no restart as this would be too annoying.

**Comment by Helium314** [comment]
Rescan after changing quest settings is not required any more if you enable _Create quests dynamically_ setting.
If this is enabled, quests in view will be newly created from current quest settings, instead of read from the database. Thanks to cache and other recent performance improvements this is working reasonably fast.

**Comment by Helium314** [comment]
I'm closing this, as such a simple boolean setting doesn't really work when quest settings are used, and also it can't be customized.
As a replacement, use per-preset quest settings and enable _Create quests dynamically_.
