### ISSUE TITLE
Black button background in dark mode

### ISSUE THREAD

**Issue by Helium314** [Helium314/StreetComplete#376]
In dark mode, almost everything has a black background, except the permanently visible buttons on main screen. I've been testing to switch them to black in dark mode (with white drawings), and find it works well.
But making this optional (i.e. button color independent of theme) would be considerably more work.

@mnalis would it be ok to non-optionally couple button background to theme? It would go against the general aim of making *everything* optional, but I can't really see why one would actually want white buttons on a dark theme.

**Comment by mnalis** [comment]
Do you have a pic of how it would look? 

It might be OK, unless it makes finding buttons noticeably harder to notice. Would the quest pins also change background? 

In worst case, we already support different themes, so we could have the familiar ones remain the same as in upstream, and the improved ones be separate themes (like for `Dark (increased contrast)` with their own button background). But it also might be fine as it is, and we only add separate themes if people complain...

**Comment by mnalis** [comment]
hmmmm... I definitely do **not** like that supposedly **"high contrast"** map has basically **no contrast at all on buttons**. Perhaps if you pretended that "high contrast" is a day map instead (how does a code know anyway which set of buttons to use?), so it would get white  buttons instead? 

Or maybe try adding a white circle outline around dark buttons, perhaps that might improve the look?

(Still, one might still tend to prefer to have on/off preference like "buttons are always white". Then if it is enabled, one gets regular upstream SC behaviour, and if disabled, buttons follow the theme. But if that is too much work / ugly code than perhaps better not do it)

**Comment by Helium314** [comment]
Well, if the name *high contrast* is the problem, then I'll just rename it. I put some name in there to have some difference between default dark theme and own dark theme.

> Or maybe try adding a white circle outline around dark buttons, perhaps that might improve the look?

That would be considerably more work, probably even more than making button color optional.

> how does a code know anyway which set of buttons to use

Android can use different xml (overlay) files for night mode, and dark mode is making use of it. See e.g. https://github.com/Helium314/StreetComplete/blob/modified/app/src/main/res/values-night/colors.xml

**Comment by mnalis** [comment]
> Android can use different xml (overlay) files for night mode, and dark mode is making use of it

So, if I understand it correctly, using current model, it is not possible to have **more than two** colors of the button (like it is possible to have more than two themes in SC?), as it is underlying android layer that forces either "light" or "dark" color for buttons, and nothing in between?

Oh well. Probably not worth the effort, then. If people complain later, we can reconsider.

> Well, if the name _high contrast_ is the problem, then I'll just rename it.

Ah, it is not the name of the theme, but the fact that the buttons are not really visible in that theme. I've tried playing with putting different shades of gray, but while it improves one, it makes it little worse on other, so I'm not sure if would be clear improvement overall:

![dark1](https://user-images.githubusercontent.com/156656/177332820-c02e1abc-87b1-40c9-b564-a3bfa2d917bf.png) ![dark2](https://user-images.githubusercontent.com/156656/177332817-2b556980-ff49-476a-a37b-abb987e2f648.png)

Anyway, I'm fine to go with your idea then if you find it the best. We can always invest extra effort later if needed...

**Comment by Helium314** [comment]
Actually I found another (semi) solution, but still need to test it: starting with Android 9, the shadow color can be adjusted. So we can simply have a black button with a white/grey shadow, similar to the white buttons being distinguishable from white background thanks to the dark shadow.
But: not working with Android 6-8.

**Comment by Helium314** [comment]
Implemented, including the light shadow for Android 9 and above.
So let's see whether there is negative feedback...
