### ISSUE TITLE
Translate 

### ISSUE THREAD

**Issue by DickerPeter** [Helium314/StreetComplete#380]
Hello, is it possible to display the quests in the system language of the device?  I would also like to support this just because I unfortunately don't like how.

**Comment by Helium314** [comment]
Currently I don't have any plan to use translation platforms like it's done for StreetComplete, so translations need to be done "manually".
This is by adding entries from https://github.com/Helium314/StreetComplete/blob/modified/app/src/main/res/values/strings.xml to `strings.xml` of other languages. You can find the files in https://github.com/Helium314/StreetComplete/tree/modified/app/src/main/res in subdirectory `values-<language>`
All entries added in this version of SC are found at the top, in the section marked with `<!-- Modifications -->`. Essentially you just need to copy the lines you want to translate into another `strings.xml` and change the text.

@mnalis you did a lot of translations for SC. Do you have any hints / tools / ideas / ...?

**Comment by DickerPeter** [comment]
That's no problem, I'll be happy to take care of that for the German part. That I would translate the corresponding additional strings accordingly and then submit them.

**Comment by DickerPeter** [comment]
An idea of ​​mine, you could as well for the original. For the modifications you have created, open a project here https://poeditor.com/ and anyone who wants to can work there in their own language.
And then they would have to be entered into Git accordingly.
That's how it's done at SC Original.
https://poeditor.com/join/project/IE4GC127Ki

**Comment by mnalis** [comment]
> @mnalis you did a lot of translations for SC. Do you have any hints / tools / ideas / ...?

Unfortunately no specials ideas... I've used POeditor.com website that upstream StreetComplete uses. Other that that, I've used `.po` files a little in other projects, but they are not well suited for StreetComplete / Android as such (as it seems to use token IDs instead of English strings).

Just to be sure @DickerPeter : we are talking here about translating quests / text that are **not present** in [upstream/original StreetComplete](https://github.com/streetcomplete/StreetComplete/blob/master/CONTRIBUTING.md#translating-the-app) project, right?

**Comment by DickerPeter** [comment]
Yes, it is about the questions and texts that are not available in the original.

**Comment by Helium314** [comment]
I'll have a look whether it's possible to make only strings added in this fork translatable, as the ones available for upstream SC should not be available here.

**Comment by Helium314** [comment]
I'm totally new to POEditor, so I hope this works: https://poeditor.com/join/project/iAUihUmKW7

**Comment by mnalis** [comment]
Wow, I have not expected **_223_** new strings to translate :open_mouth: ! 

I've translated a few so we can see if translation works, but it will take some time to finish...

**Comment by Helium314** [comment]
I also noticed this is quite a lot when I copied it to the separate file...
Probably more than half of it is for all the additional (quest and normal) settings

**Comment by mnalis** [comment]
It seems to be working - my translations (e.g. `pref_3d_buildings_title` are shown in SC EE in Croatian, when it is selected as an app language)!

So @DickerPeter, please visit https://poeditor.com/join/project/iAUihUmKW7 and add translations for your language (and/or encourage other speakers of your language to do it), and translations should be included in next SC EE releases then!

**Comment by DickerPeter** [comment]
But I'm looking for that for the whole app and not just half measures, but that's apparently not wanted.

**Comment by Helium314** [comment]
What do you mean by that? You want to translate the *whole* app again, even though the original SC strings are already translated or translatable in https://poeditor.com/join/project/IE4GC127Ki?

**Comment by mnalis** [comment]
> But I'm looking for that for the whole app and not just half measures, but that's apparently not wanted.

@DickerPeter I think you misunderstood something, there are **no** "half-measures", and it is indeed much wanted to help you. However, I cannot translate to _your_ language (unless by chance your language happens to be Croatian) - such translation can only be done by someone like **_you_** who understands **_your_** language.

So **Whole** of "StreetComplete EE" app will be translated in your language (i.e. "**no** _half-measures_"!) when:

- all the "base" StreetComplete strings are translated via https://poeditor.com/join/project/IE4GC127Ki , _**and**_
- all the "extra" EE strings are translated via https://poeditor.com/join/project/iAUihUmKW7

If your language is present in upstream StreetComplete, it should indeed **_much preferred by everyone_** to just translate missing few **hundreds** strings, than to translate **thousands** of strings from scratch (even if they were already translated)!
