### ISSUE TITLE
give better filename to .apk releases

### ISSUE THREAD

**Issue by mnalis** [Helium314/StreetComplete#382]
**Use case**

Currently, GitHub releases are **all** named `app-release.apk`. This is not ideal.

**Proposed Solution**

Upstream releases are named like `StreetComplete-v45.2.apk`.
It would be great if we also could name them like `StreetComplete-EE-v45.2.apk` or similar.

**Comment by peternewman** [comment]
It looks like this part is failing for some reason:
https://github.com/Helium314/StreetComplete/blob/026f9acc9466c797094757ef09c719da775c9172/.github/workflows/build-signed-apk.yml#L29-L30

**Comment by Helium314** [comment]
@mnalis do you mean the workflow?

The apks on the releases page are lazily not renamed, but I can give a different name to the next versions.

**Comment by mnalis** [comment]
No, the workflow should work fine (it does on upstream SC). 
I've meant the release page at https://github.com/Helium314/StreetComplete/releases

**Comment by Helium314** [comment]
Done with the latest release.
(I hope I won't forget this later...)
