### ISSUE TITLE
Allow editing of raw tags in overlay mode

### ISSUE THREAD

**Issue by deevroman** [Helium314/StreetComplete#386]

**Comment by Helium314** [comment]
done in https://github.com/Helium314/StreetComplete/commit/1180e5975d1d883447dc512a90e110896112608c

**Comment by NotSoImportant** [comment]
What kind of syntax do I need to use in the custom overlay dialog?

**Comment by Helium314** [comment]
The syntax is described in
https://github.com/Helium314/StreetComplete/blob/modified/CONTRIBUTING_A_NEW_QUEST.md#element-selection
and
https://github.com/Helium314/StreetComplete/blob/modified/app/src/main/java/de/westnordost/streetcomplete/data/elementfilter/ElementFilterExpression.kt

Only difference is that the node/way/relation checkboxes take care about the `nodes, ways with` part.

I will add a link to the documentation in the _custom overlay_ menu.

**Comment by NotSoImportant** [comment]
Thanks. Now I am able to use it 👍
Is it only possible to color the road center green on match, or how could I color differently with different queries/values? And how to color right and left side of the road (like for sidewalk quest)?

**Comment by NotSoImportant** [comment]
Looking at [CustomOverlay.kt](https://github.com/Helium314/StreetComplete/blob/modified/app/src/main/java/de/westnordost/streetcomplete/overlays/custom/CustomOverlay.kt)  it does not look like this is possible right now, is it?

**Comment by NotSoImportant** [comment]
By the way: editing custom overlay can easily crash the app. Probably parsing should only be done when hitting "ok" button

**Comment by Helium314** [comment]
> Looking at [CustomOverlay.kt](https://github.com/Helium314/StreetComplete/blob/modified/app/src/main/java/de/westnordost/streetcomplete/overlays/custom/CustomOverlay.kt) it does not look like this is possible right now, is it?

Yes. Custom overlay only allows rather simple element selection without anything else. Customizing the display style is technically possible, but would be a lot of effort to implement.

> By the way: editing custom overlay can easily crash the app. Probably parsing should only be done when hitting "ok" button

This is weird... it should never crash, but instead catch the exception and show a message:
https://github.com/Helium314/StreetComplete/blob/3f0e90ab24793e06af2879f9ec83db77effe8127/app/src/main/java/de/westnordost/streetcomplete/screens/main/overlays/OverlaySelectionDialog.kt#L88-L94

**Comment by NotSoImportant** [comment]
So maybe crash was not directly happening from this piece. However while/after writing the selection code sometimes the error message stayed persistent even after changing to valid code.

**Comment by Helium314** [comment]
Did you get a crash report? That should help identifying the cause.

`Toast` is something managed by Android, it's only possible to select "long" or "short". If the message stays longer than a few seconds there is nothing I can do.
