### ISSUE TITLE
Reduce mis-taps when trying to scan for quests

### ISSUE THREAD

**Issue by Helium314** [Helium314/StreetComplete#388]
With the overlays, team mode was moved below "scan for quests" button. Due to the small button size it's rather easy to accidentally enable team mode when trying to scan for quests.

@mnalis I think you had some solution for this. Does it actually work, or was it just a mockup?

**Comment by mnalis** [comment]
Yup, it works and there I no longer misclick on team mode:

![small_Screenshot_20220903_212158_de westnordost streetcomplete mn debug](https://user-images.githubusercontent.com/156656/188285143-d17ee1d5-385b-44d3-84d1-66df813abe4a.jpg)

However, as I still also use upstream SC, I find different menus between them **_almost_** as annoying as the original problem of misclicking on team mode, as it prevents my muscle memory for settling for new layout :cry: 

(related: https://github.com/streetcomplete/StreetComplete/discussions/4130 and https://github.com/streetcomplete/StreetComplete/discussions/4113#discussioncomment-2996550)

perhaps westnordost might reconsider changing it... That would be the ideal solution.

**Comment by Helium314** [comment]
Hmm, I see...
It's https://github.com/mnalis/StreetComplete/tree/ui-hamburger-2x3, right?
I'll see whether I can make it optional.

> perhaps westnordost might reconsider changing it... That would be the ideal solution.

Judging by his reply, I guess not (at least not soon)

**Comment by mnalis** [comment]
>  It's https://github.com/mnalis/StreetComplete/tree/ui-hamburger-2x3, right?

Yup, that's it.
