### ISSUE TITLE
Allow AR width for all streets

### ISSUE THREAD

**Issue by HolgerJeromin** [Helium314/StreetComplete#389]
I was at a really narrow residential street and wanted to measure its width.
It would be nice to have this for all streets as an option.

**Comment by Helium314** [comment]
Actually for `highway=residential` width should already be asked if there are no lane markings or less than 2 lanes.
So I'm not sure what actually would need to be adjusted.
I could simply allow customizing 
https://github.com/Helium314/StreetComplete/blob/354b2cdd312a76fb01c52ab306a799a32d16a6c4/app/src/main/java/de/westnordost/streetcomplete/quests/width/AddRoadWidth.kt#L26-L44
but that may be a little too much

**Comment by HolgerJeromin** [comment]
https://www.openstreetmap.org/way/27100679/history
# 8 was my way. I had no width quest.

**Comment by Helium314** [comment]
I see... you could only get the width quest if you answer the lanes quest, which requires maxspeed > 33 (but not something like urban default limit).

For me the easiest thing would be allowing to customize the whole thing, or maybe rather the
```
           ( 
             highway ~ trunk|primary|secondary|tertiary|unclassified|residential 
             and (lane_markings = no or lanes < 2) 
           ) or ( 
             highway = residential 
             and maxspeed < 33 
             and lane_markings != yes and (!lanes or lanes < 2) 
           ) 
           or highway = living_street 
           or highway = service and service = alley 
```
part

**Comment by Helium314** [comment]
The quoted part is now customizable: https://github.com/Helium314/StreetComplete/commit/78f97ad5da84028333db5961c5ab9e3a486bd364

Will be in next release
