### ISSUE TITLE
The ability to save photos to notes on the device

### ISSUE THREAD

**Issue by deevroman** [Helium314/StreetComplete#393]
via https://github.com/streetcomplete/StreetComplete/discussions/2396

It seems that the expert edition of StreetComplete can afford the settings item to save photos to the device in full quality and request additional permission for this.

**Comment by Helium314** [comment]
Sure this could be done. Maybe it can even be done without additional permission in manifest, if access permission granted when using `ACTION_OPEN_DOCUMENT_TREE` is permanent.

Not sure when I find time to implement this, but If anyone wants to do a PR it would probably be done faster.

**Comment by Helium314** [comment]
I solved it like getting gpx files: You'll need to use an option in the note preferences screen (or get the files with some file explorer app from `Android/data/de.westnordost.streetcomplete.expert/files`)
