### ISSUE TITLE
Better arrangement of EE preferences

### ISSUE THREAD

**Issue by Helium314** [Helium314/StreetComplete#396]
Currently preferences added in EE are simply a long list, and probably soon it's going to be a very long list.

It would make sense to group the settings into a few meaningful categories, and have a (sub)menu for each category.
Help / suggesions with arrangement of groups and actual implementation is very welcome.

**Comment by mnalis** [comment]
One bigger group of tasks I see seem to be about `notes`. Another is `data managment` (import/export, load tree/data, SD storage, autodownload/redownload, delete old data after, get gpx). Others might be specific `display` modification (maybe merged with extra `UI elements`) - problem is that one partially overlaps with `notes`, though.

**Comment by Helium314** [comment]
Thanks!

Currently there is
* quick settings button
* show nearby quests
* show next quest immediately
* move recent answers to front
* show all main menu items as grid
* hide button
* GPX note button
* swap OSM and GPX buttons
* hide keyboard before creating note
* close quest form immediately
* volume button zoom
* select first edit when opening edit history
* show 3D buildings
* show quest geometries
* remove marker offsets
* show solving animation
* location intervals (maybe remove it, I used it to set my GPS interval to 0, which is now default)
* auto download
* always re-download
* delete data after
* tiles on SD card
* daytime quest filter
* hide notes by users
* advanced resurvey
* per-preset quest settings
* dynamic quest creation
* nearby quest notification
* external & tree files (should be moved to quest settings, but I didn't find a way to start the file selection from quest settings)
* import/export
* GPX note file

So some attempt, without aiming to cover _all_ settings (only categories, order is not relevant)
* Notes
  * GPX note file
  * GPX note button
  * swap OSM and GPX buttons
  * hide keyboard before creating note
  * hide notes by users
* display
  * show 3D buildings
  * show quest geometries
  * remove marker offsets
  * show solving animation
* UI
  * hide button
  * quick settings button
  * show nearby quests
  * show next quest immediately
  * move recent answers to front
  * show all main menu items as grid
  * select first edit when opening edit history
* data management
  * auto download
  * always re-download
  * delete data after
  * tiles on SD card
  * external / tree files
  * import / export
* quest things (to be renamed)
  * advanced resurvey
  * per-preset quest settings
  * dynamic quest creation
  * nearby quest notification

As you noted, _UI_ and _display settings_ overlap a bit, but there would be too many settings again if both were in the same category. Also _quest things_ and _data management_ overlap somewhat.

**Comment by Helium314** [comment]
done in https://github.com/Helium314/StreetComplete/commit/48c1a288a398a1226f04420c0ecf5a6483e5e2f7
