### ISSUE TITLE
Option to add a custom imagery url

### ISSUE THREAD

**Issue by meiphoo7-Mae** [Helium314/StreetComplete#398]
**Use case**

Currently it is possible to replace the map by satellite imagery. However in my country there's a governmental service that produces aerial imagery once a year using a helicopter. Of course this imagery is much more detailed than the satellite imagery.
So it would be great if I could change the URL of the imagery used.

**Proposed Solution**

Well, I'm not exactly an expert in the inner workings of SC and/or SC-ee but in Vespucci and in JOSM it is possible to select imagery from a list that is included in the software and additionally in JOSM it is even possible to add an URL, provided that the user knows how a valid URL is constructed.

**Comment by meiphoo7-Mae** [comment]
Both JOSM and Vespucci can handle WMS/WMTS based services, so that involves x, y and zoom if I'm correct. Also the service which I prefer is WM(T)S based. As an addition to the proposed solution: I assume the current imagery service is hard-coded. Perhaps it is possible (as a starting point) to create an input form for the URL pre-populated with the current URL  and leave it to the user how the URL should be constructed if the user decides to change it. After all this is the Expert Edition, so a user not knowing how to do this should not touch it (similar to other options in this version).

**Comment by Helium314** [comment]
> I assume the current imagery service is hard-coded. Perhaps it is possible (as a starting point) to create an input form for the URL pre-populated with the current URL and leave it to the user how the URL should be constructed if the user decides to change it

Yes, and changing the URL works only if the new URL contains zoom, x and y, as these are the only variables that are resaonably simple to use without changing much more. That's the requirement I stated above.

**Comment by Helium314** [comment]
done in https://github.com/Helium314/StreetComplete/commit/28d3acbd835b04dbb139b13e40db76689db882da

**Comment by govvin** [comment]
@Helium314 , some URLs uses "{zoom}" rather than {z}, and the validator specifically looks for the latter in URLs.

> done in [28d3acb](https://github.com/Helium314/SCEE/commit/28d3acbd835b04dbb139b13e40db76689db882da)
