### ISSUE TITLE
Constant crashes in version 48

### ISSUE THREAD

**Issue by meiphoo7-Mae** [Helium314/StreetComplete#399]
Doing about anything (like going to settings) causes an immediate crash. The app actually does not crash permanently but enters a "minimized" state and when "maximized" again it shows that the app has crashed previously and sometimes offers to send an E-mail with debug information, which I pasted below, but it is possible to resume the activity. So the crash apparently is not fatal, but it is annoying and interrupts workflow.

**How to Reproduce**

As far as I can tell there's nothing specific needed. Just do an action and it crashes.

**Expected Behavior**

I don't want to see crashes.

**Versions affected**

Version 48 on Android 10.

 
The app suggests the following is useful:

Thread: main
App version: 48.0_ee
Device: OPPO  OP4F2F, Android 10
Locale: nl
Stack trace:
java.lang.AbstractMethodError: abstract method "void android.location.LocationListener.onProviderDisabled(java.lang.String)"
at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:365)
at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:275)
at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:291)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:240)
at android.app.ActivityThread.main(ActivityThread.java:7829)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)

**Comment by meiphoo7-Mae** [comment]
Reading the above once again:
The "LocationListener.onProviderDisabled" statement above triggered my attention. It appears that turning "Notify about nearby quests" (under EE setttings > Quests) while the GPS is turned off is responsible for the crash.

**Comment by Helium314** [comment]
Did you use EE before? If so, which version?
This could help pointing towards the issue (there is no app code in the crash log, so it's not so simple to find).

**Comment by Helium314** [comment]
> Reading the above once again: The "LocationListener.onProviderDisabled" statement above triggered my attention. It appears that turning "Notify about nearby quests" (under EE setttings > Quests) while the GPS is turned off is responsible for the crash.

Great, so that should help a lot.

**Comment by Helium314** [comment]
Could you try https://github.com/Helium314/StreetComplete/releases/tag/v48.0_ee_fix?

**Comment by meiphoo7-Mae** [comment]
I tried the fixed version and the app does not crash anymore. Thanks for your swift response.

**Comment by Helium314** [comment]
Thanks for testing, and especially the hint towards nearby quests!
