### ISSUE TITLE
Left and right coloring for custom overlay

### ISSUE THREAD

**Issue by SLMapper** [Helium314/StreetComplete#403]
**Use case**
Coloring the left and right side of a street instead of it's center
E.g. for a custom bicycle overlay 

**Why**
Coloring custom overlay based on tags is nice, but creates too many colors when _left_, _right_ and _both_ is included in the keys. 

**Proposed Solution**
When coloring key matches a key containing _:left_, _:right_ or _:both_, colors the left, right or both side(s) of the street instead (like the bicycle or sidewalk quest)

**Comment by Helium314** [comment]
This was a lot easier to implement than I had thought.
Done in https://github.com/Helium314/StreetComplete/commit/87ed5ac3e112f2e365d19664e85033937dc2be3d

**Comment by SLMapper** [comment]
Wow, this is amazing 🚀
Is there a way to test out a pre-release / custom build or should I just wait for the next release?

**Comment by Helium314** [comment]
Can you access the apk in https://github.com/Helium314/StreetComplete/actions/runs/3862791000 or https://github.com/Helium314/StreetComplete/suites/10237767872/artifacts/501994705?

**Comment by tiptoptom** [comment]
Could you also support forward/backward?

**Comment by rusty-snake** [comment]
@tiptoptom this is a different feature, open a new feature request for it. Adding a comment to a closed issue after nearly two years does not bring it to on the agenda and pollutes search and history.

Beside that, do you have an suggestion where/how it should be displayed?
