### ISSUE TITLE
Custom overlay edit windows does not scroll

### ISSUE THREAD

**Issue by SLMapper** [Helium314/StreetComplete#405]
**How to Reproduce**
Add multiple lines of text. Afterwards the coloring section cannot be reached
![IMG_20230107_145205.jpg](https://user-images.githubusercontent.com/104768113/211154502-761c90fe-6a85-48df-bf98-3914156397cf.jpg)

**Expected Behavior**
Edit windows or whole popup gets a max-height to enabled scrollbars when height gets bigger 

**Versions affected**
50.1_ee

**Comment by Helium314** [comment]
solved in https://github.com/Helium314/StreetComplete/commit/61d64d29e35a0f16f18e3edb29693ffb5a023f21
