### ISSUE TITLE
New Quest: Which brewery is the beer served here?

### ISSUE THREAD

**Issue by mcliquid** [Helium314/StreetComplete#472]
Quest idea based on: https://github.com/streetcomplete/StreetComplete/issues/82

### General
Affected tag(s) to be modified/added: [brewery](https://wiki.openstreetmap.org/wiki/Key:brewery)
Question asked: **Which brewery is the beer served here?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/Helium314/SCEE/blob/modified/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give should have an equivalent tagging (SCEE quests may not be answerable in all cases, but please keep this rare)
- [ ] 🐿️ A survey is necessary (may require knowledge of the subject, though easy answering for everyone is preferred)
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
```
nodes, ways with
             (
                 amenity ~ bar|biergarten|pub|restaurant|nightclub
                 and !brewery
             )
```

**Proposed UI:**
Quest icon already added: https://github.com/streetcomplete/StreetComplete/pull/938/commits/56d3ae659efaf3f6e9797fd860f6eb2b9092c393

I would use the same implementation as the `cuisine` quest, since you can select multiple values from a list.

**Comment by Helium314** [comment]
Should be good, also the UI.

Some details to consider:
* Suggestions like for the cuisine quest would be nice, but certainly not necessary
* Suggestions could also come from nearby places with `brewery`, similar to the destination quest.
* Values entered by the user should be stored / added to the suggestions (maybe that already works for the cuisine quest, not sure)
  * Maybe even those nearby values could be stored to build a local list of suggestions. Not sure if this is feasible though.
* The example in the wiki "_e.g. `brewery=Krombacher` where draft beer comes from  Krombacher Brauerei_" implies `brewery` is only about draft beer, but that's not mentioned explicitly. "_The `brewery=*` tag should be given for restaurants, bars, pubs, and similar features for indicating which breweries' beer they have available._" can also be interpreted as _any_ beer.
This should be clarified in the question, and possibly also in the wiki.
