### ISSUE TITLE
Auto-complete not working for tree names with whitespace

### ISSUE THREAD

**Issue by ElFrogster** [Helium314/StreetComplete#547]
**How to Reproduce**
When entering the genus/species of a plant (maybe in other cases of having to enter a name somewhere too) the auto-complete does not work as expected. Plant names usually have two parted names like "tilia cordata". As long as you type the name up to "tilia ", autocomplete still shows a list of possible matches. But when typing "tilia c" all suggestions disappear, even though "tilia cordata" was still in the list of possible fits before typing the "c"

**Expected Behavior**
The list of suggestions should still show when starting to type the second part of the name.

**Does it happen in normal StreetComplete?**
StreetComplete does not have the tree species feature. Not sure if it has auto-complete for other features and whether the issue comes up there, too.

**Versions affected**
F-Droid 57.4

**Comment by Helium314** [comment]
I don't intend to spend time on this as it's a minor issue and the tree quest is rarely used, but if anyone wants to fix it: have a try.
