### ISSUE TITLE
GPS button is hardly visible in dark modes in 58.0

### ISSUE THREAD

**Issue by mnalis** [Helium314/StreetComplete#550]
It looks like this:

![small_Screenshot_20240604_144405_SCEE1](https://github.com/Helium314/SCEE/assets/156656/b8a3fc67-ae80-4382-b0e2-8490c4be892c) ![small_Screenshot_20240604_144346_SCEE1](https://github.com/Helium314/SCEE/assets/156656/e21f2b06-fbec-4554-8fe6-d1ab33b1606a) ![small_Screenshot_20240604_144707_SCEE1](https://github.com/Helium314/SCEE/assets/156656/83acb3bf-fa2e-42fe-93bb-464779f7fde8)

note that when you are at exact GPS location it is visible, because inner part of the button turns orange, and orange-on-black is visible. But if you move away,  it turns to (almost)black-on-black, which is not visible.

**How to Reproduce**
- Select either of two dark modes in settings
- return to the main map screen
- pan a map a little

**Expected Behavior**

The button details would be visible, i.e. white-on-black (like the zoom buttons `+` and `-`), and not almostblack-on-black

**Does it happen in normal StreetComplete?**
Not in SC 57.4 (I don't have SC 58.0 yet, but as they always use light buttons even in dark mode, I don't think the issue would happened there).

**Versions affected**
Android 14, SCEE 58.0 - I think it the bug was not present in SCEE 57.x series.

**Comment by mnalis** [comment]
Confirming that the bug does not happen in vanilla StreetComplete 58.0, so it is SCEE-specific.

**Comment by FloEdelmann** [comment]
Relevant commit: https://github.com/streetcomplete/StreetComplete/commit/7a40b562cc6251a03eda951b6319cd5c170243ea
