### ISSUE TITLE
Add 'mall' as a building type

### ISSUE THREAD

**Issue by realeatham** [Helium314/StreetComplete#554]
A mall is a distinct building which doesn't fit as any of the current building types and is already used in osm.

**Comment by mnalis** [comment]
If we are talking about "building type" quest/overlay, `building=mall` seems to be deprecated and undocumented in OSM wiki, see https://wiki.openstreetmap.org/wiki/Tag:building=retail (which is also recommended replacement)

You may wish instead to tag [shop=mall](https://wiki.openstreetmap.org/wiki/Tag:shop=mall) which is used to indicate **actual** mall which end users might want to find. That can be tagged in `Places overlay`, unfortunately only as point (not on existing building polygon, which would be more useful -- but that is only possible in SCEE's _"expert mode"_ via manual raw tag editing, which is admittedly somewhat unergonomic)

See also  [regular SC FAQ: Building Type Quest - Why don't I see the right types?](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Building_Type_Quest_-_Why_don't_I_see_the_right_types?) / https://github.com/streetcomplete/StreetComplete/issues/3868 etc.
