### ISSUE TITLE
Translation missing

### ISSUE THREAD

**Issue by Mr-Update** [Helium314/StreetComplete#555]
German translation is missing for Settings -> Data management -> "Use temp logger" and the next line.
The translation is also missing in all other languages.

![Logger](https://github.com/Helium314/SCEE/assets/37781396/70ee0c9b-db05-4bdd-8e08-97e71c50cf08)

**Comment by Helium314** [comment]
Let me remind you of the following part of the bug report template:
> Attaching screenshots / videos:
Large images / videos can be very disturbing when reading, so please avoid attaching unnecessary screenshots and videos.
If you think they are needed, reduce the size or use thumbnails to keep the issue nicely readable.
