### ISSUE TITLE
Settings gear aperas on normal overlays

### ISSUE THREAD

**Issue by rusty-snake** [Helium314/StreetComplete#580]
Settings gear aperas on normal overlays.

![ResizedImage_2024-07-09_15-18-51_2641](https://github.com/Helium314/SCEE/assets/41237666/5b0329c5-3b5a-476b-9b06-b6cb079dba63)

**How to Reproduce**
- Add custom overlays (more than fit on screen)
- Open overlay menu
- Scroll down
- Scroll up
- See overflowing settings icons

**Expected Behavior**

No settings icons in normal overlays.

**Does it happen in normal StreetComplete?**

SCEE feature

**Versions affected**

- Pixel 6
- GrapheneOS (AOSP 14 QPR 3)
- SCEE 58.2

**Comment by Helium314** [comment]
I guess that's another thing I won't bother fixing at this point. The whole app is moving to compose, which requires completely re-writing that menu anyway.

**Comment by rusty-snake** [comment]
Fixed in SCEE 60.0

**Comment by Helium314** [comment]
Thanks for noticing! I stumbled upon tis bug when comparing old and new overlay dropdowns, and didn't remember there was an issue about it.
