### ISSUE TITLE
Add Address or a general entry for address mapping

### ISSUE THREAD

**Issue by cyberchrime** [Helium314/StreetComplete#585]
**Use case**

I regularly use SCEE to add missing addresses to buildings, which are already mapped on OSM. For buildings with only a singe address this works very well. However, I often find buildings which are mapped as a single building, but have multiple addresses.

**Proposed Solution**

Currently, to add multiple addresses to a singe building, I add a node to the building and set the node type to _Main Entrance_ or _Staircase Entrance_, as they can additionally hold address tags. Unfortunately, in many cases these entry types do not fit perfectly the actual entrance type. Instead, I would often like to add a general entrance (entrance=yes) or simply a POI which represents an address.

**Comment by HolgerJeromin** [comment]
With the address overlay you can add house numers on the outline of buildings. Those nodes will get `entrance=yes`

**Comment by Helium314** [comment]
Your use case seems to be already covered by the address overlay. You can add addresses to buildings, you can add address nodes, and you can add entrance nodes.

**Comment by cyberchrime** [comment]
Hi, many thanks for your replies. Your hints made me realize that this use case can be achieved with the big red (+) at the bottom (which I totally overlooked) while in address overlay
