### ISSUE TITLE
Better outdoor seating quest

### ISSUE THREAD

**Issue by vfosnar** [Helium314/StreetComplete#589]
There seems to be confusion around patio, terrace, balcony and veranda.

https://wiki.openstreetmap.org/wiki/Tag:outdoor_seating%3Dpatio
> in OSM, this tag is applicable to any terrace.

I propose removing patio as an option to reduce confusion.

For other tags it would be nice to add a short description explaining their differences. Something like:
- terrace: ?
- balcony: not on the ground floor
- veranda: roofed, slightly above ground

**Comment by mnalis** [comment]
- (ref. for auto-linking: https://github.com/streetcomplete/StreetComplete/issues/5775)

**Comment by mcliquid** [comment]
Patio is translated as "Innenhof" (like inner courtyard?) in German. At least in the German translation, this is clearly distinguishable for me from the other values.

I've asked AI what the term "Patio" does mean in German, the English translation of the output is:
> A ‘patio’ is an open inner courtyard that is often found in Spanish or Spanish-influenced architectural styles.

**Comment by vfosnar** [comment]
The OSM wiki states it is an equivalent to terrace but we could keep patio and just add an explanation too.

**Comment by Helium314** [comment]
I also find it a weird value that requires clarification.
See also the [second image on wikipedia](https://en.wikipedia.org/wiki/Patio), which does not work at all with "_A ‘patio’ is an open inner courtyard that is often found in Spanish or Spanish-influenced architectural styles._" or with the [patio example image on OSM wiki](https://wiki.openstreetmap.org/wiki/Key:outdoor_seating).

I would clearly tag the OSM wiki image as street, not sure about the wikipedia image (it's a fenced area on the sidewalk, but so far I tagged `sidewalk` only without the fence).

Anyway, just removing the value may avoid confusion (and possibly ambiguous tagging), but at the same time there is need for some replacement.

**Comment by robertgzr** [comment]
> Patio is translated as "Innenhof" (like inner coutyard?) in German

and more often as "Terasse" (aka terrace): https://www.dict.cc/?s=patio which is really not helpful :/ but the [german wikipedia entry about patio](https://de.wikipedia.org/wiki/Patio) says it's a courtyard in spanish/portugese architecture. in australian english it means the same as veranda/porch

what would really help here is attaching example pictures to the values, i find myself looking up the definitions of each option every time i encounter it

**Comment by robertgzr** [comment]
from reading at the least the german and english wikipedia articles for the values listed [here](https://wiki.openstreetmap.org/wiki/Key:outdoor_seating) they often depend on locale :sweat_smile: so not sure what to do with that
