### ISSUE TITLE
Fine to remove `OsmElementQuestType::getTitleArgs`?

### ISSUE THREAD

**Issue by westnordost** [Helium314/StreetComplete#598]
No StreetComplete quest has been using this functionality for a while now because *naming* (feature type, `name`, `ref`, `operator`, ...) has been moved to a separate text field. I am contemplating whether to remove it to simplify the code a bit.

I see a few usages in SCEE, but I am not sure whether these are all cases that could easily or should rather go into that separate "name" text field displayed below the question.
I think if there is a valid use case for this feature left in SCEE, it is not worth to remove it in SC, but otherwise I would like to remove it from SC.

**Comment by Helium314** [comment]
I think it's fine to remove it. There are some cases where tags are shown, e.g. in the fixme "quest", but it's also possible to adjust the title text when opening the quest form...

**Comment by westnordost** [comment]
Okay, thanks!
