### ISSUE TITLE
check_date:check_date:crossing

### ISSUE THREAD

**Issue by rusty-snake** [Helium314/StreetComplete#602]
https://www.openstreetmap.org/changeset/155359796

All double check_dates were added by `StreetComplete_ee 58.21`. <sub>I only checked samples.</sub>

SCEE released the code that does this (so the fix need to be released here). However maybe it is derive from SC `master` that has recent changes (https://github.com/streetcomplete/StreetComplete/commit/8d488a0eb5b4410682b3713e9986391abd6f0e4f) regarding check_date. So ping @westnordost too.

**Comment by mcliquid** [comment]
This feature was added here: https://github.com/Helium314/SCEE/pull/572
I've created a PR to fix this issue in #604

**Comment by mcliquid** [comment]
@Helium314 Would it be good to release a ‘bug fix’ version?

**Comment by HolgerJeromin** [comment]
Should the code allow both variants?
Or somehow report this misusage (optimal at compile / test time)?

**Comment by Helium314** [comment]
Looks like I missed [my own list of open issues](https://github.com/Helium314/SCEE/pull/572#issuecomment-2231343654) with this quest when merging... so I guess I'll fix that stuff too.

> Should the code allow both variants?

What do you mean?

**Comment by rusty-snake** [comment]
> What do you mean?

There could/should be an `debug_assert(!key.startswith("check_date:"))`.

**Comment by Helium314** [comment]
> There

Where?

What is `debug_assert` supposed to do?

**Comment by HolgerJeromin** [comment]
>>  Should the code allow both variants?

> What do you mean?

`tags.updateCheckDateForKey` could remove `check_date` from the input.

**Comment by rusty-snake** [comment]
I'm not a Kotlin dev so I can not answer the implementation.

> What is debug_assert supposed to do?

Fail (e.g. throw an exception) if argument is `false` in debug build. In release builds it is optimized away.
