### ISSUE TITLE
Backup/restore settings to file

### ISSUE THREAD

**Issue by Atrate** [Helium314/StreetComplete#606]
**Use case**
Sometimes I need to migrate SCEE to another device or wipe data to fix an issue, like #605. In that case I need to manually restore my quest selection (fixable with "sharing a preset", custom quest settings (not fixable with the aforementioned solution) and app settings, of which there are many in SCEE.

**Proposed Solution**

It'd be nice if there was a simple way to backup all settings, including quest selection and customizations, to a file on the device.

**Comment by rusty-snake** [comment]
So what's missing in "Settings > Datamanagment (last entry) > Settings export (bottom)"?

**Comment by Atrate** [comment]
It seems the only thing that's missing is my eyesight. Thank you.
