### ISSUE TITLE
Can't enable any quest after "is it lit?" 

### ISSUE THREAD

**Issue by RubenKelevra** [Helium314/StreetComplete#611]
I noticed that it's impossible to enable quests below the quest for "is it lit?". 

**Screenshots**

https://github.com/user-attachments/assets/04c5e75d-7334-4eed-a9a0-e356ad339863

**How to Reproduce**
- Open settings
- go to quest list
- try to enable any quest below the "is it lit" quest

**Expected Behavior**
Quest should be enable-able 

**Does it happen in normal StreetComplete?**
Nope

**Versions affected**
59.0 Alpha 1

**Comment by mnalis** [comment]
@RubenKelevra did you close this on purpose or ...?

**Comment by RubenKelevra** [comment]
@mnalis I realized that this also happens in the stable version. So I think that's on purpose.

So it's more of a usability/POLA issue than an actual bug. If you enable the "Expert Mode" switch in the settings first, those quests can be activated - but that's nowhere explained.

First time I configured SCEE I probably activated the switch "Expert Mode" first, thus I never ran into this issue.

**Comment by Helium314** [comment]
> but that's nowhere explained

I updated the readme

**Comment by riQQ** [comment]
For reference: f4a40017a1542b8ea941ecf87e427293982d63f1
