### ISSUE TITLE
Allow screen rotating during (possible) password prompting

### ISSUE THREAD

**Issue by Peter0** [Helium314/StreetComplete#616]
**Use case**
Password entering is currently unneccesary difficult

**Proposed Solution**
When the user is prompted to enter a password, e.g. when requesting the OAuth-authorisation (which looks like being delegated by SCEE to a browser instance), enable screen rotating.
Screen rotating is apparently disabled when executing SCEE for whatever reason, but consider enabling it during a password prompt.

**Why?**
Some virtual keyboards offer different keyboard layouts depending on whether screen is rotated in landscape or portrait mode. In my case, only in landscape mode I got an ample, more PC-like keyboard layout. Most passwords are memorised not in a direct char by char manner, but rather in shapes the fingers move around or as combination of basic chars and held modifier keys. Thus, to me it is almost impossible to enter a passwort using a virtual keyboard in portrait mode orientation.

Just to be clear: By "enabled screen rotating" I mean the feature that screen content and layout is following the orientation the device is held.

**Comment by Helium314** [comment]
Is this a SCEE only thing? If not I suggest to ask in SC repository.

**Comment by Peter0** [comment]
I never used SC. But this sounds sensible.

**Comment by Peter0** [comment]
Done. Ref. https://github.com/streetcomplete/StreetComplete/issues/5838

**Comment by Helium314** [comment]
Thanks! So if this gets implemented it's a little less work for me (merging upstream), and benefits more users.

**Comment by westnordost** [comment]
It will be implemented in StreetComplete
