### ISSUE TITLE
"Uhh..." -> "It's a tree stomp now" on tree leave type/species quest 

### ISSUE THREAD

**Issue by RubenKelevra** [Helium314/StreetComplete#622]
**Use case**
Sometimes trees get cut down and when you pass them, you see just a tree stomp left. 

**Proposed Solution**
Would be nice to have an easy way to answer this in the tree leave type/species quest, instead of having to switch to the tag view and edit there tags manually. 

**Screenshot**

![Screenshot_2024-08-26-20-50-17-408-edit_de westnordost streetcomplete expert](https://github.com/user-attachments/assets/f92019e2-50a2-4ba8-a477-cf4ed369bdbd)

**Comment by FloEdelmann** [comment]
Was this suggested (and rejected) at upstream StreetComplete already? It seems to me that it would also make sense for the `AddTreeLeafType` quest there.

**Comment by RubenKelevra** [comment]
@FloEdelmann isn't that the quest in the picture?

**Comment by FloEdelmann** [comment]
Yes it is, but that is an upstream StreetComplete quest, not an SCEE-specific one.

**Comment by mnalis** [comment]
Thanks @FloEdelmann, suggested at https://github.com/streetcomplete/StreetComplete/issues/5852 (and put PR in Draft until we hear back, as not to complicate the potential merge)

**Comment by HolgerJeromin** [comment]
Now merged at upstream 🎉

**Comment by mnalis** [comment]
> Now merged at upstream 🎉

First half is (Leaf type quest). The second part (Tree species/genus) still remain to be implemented in SCEE in https://github.com/Helium314/SCEE/pull/625

**Comment by RubenKelevra** [comment]
> Yes it is, but that is an upstream StreetComplete quest, not an SCEE-specific one.

Ah! I missread your question. Thanks for the clarification :)
