### ISSUE TITLE
Typo in ElementFilterExpression.kt

### ISSUE THREAD

**Issue by davidpnewton** [Helium314/StreetComplete#634]
In the documentation for element selection the following can be found:

'foo < 3.3' has a tag with key 'foo' whose value is smaller than 2.5

Think you meant smaller than 3.3!

**Comment by FloEdelmann** [comment]
Good catch! I fixed it in upstream StreetComplete: https://github.com/streetcomplete/StreetComplete/commit/4a460fe4fd6bbbca1387ef9db0394a4da860edef
It will be pulled to SCEE soon.

**Comment by mnalis** [comment]
Fixed upstream in https://github.com/streetcomplete/StreetComplete/commit/4a460fe4fd6bbbca1387ef9db0394a4da860edef
