### ISSUE TITLE
SCEE setting submenu lacking back button and header text

### ISSUE THREAD

**Issue by HolgerJeromin** [Helium314/StreetComplete#640]
SCEE 59.0-alpha2 on Android 14 on a Motorola device.

The SCEE specific setting submenus have no back icon on the top left:

![Screenshot_20240905-075051](https://github.com/user-attachments/assets/ac353f22-dc9d-4c83-97bb-0c9f1dd8b5c2)

Note: The first "row" is correctly blank in the screenshot as it is covered by android menu.

**Comment by mnalis** [comment]
I can confirm missing back button even on SCEE `58.2` on my Android 14 (Samsung Galaxy S23+), both with navigation buttons and with gesture mode:

![small_Screenshot_20240905_143555_SCEE](https://github.com/user-attachments/assets/409f1f34-8bc2-4772-955a-70038bb3cc4c) ![small_Screenshot_20240906_022520_SCEE](https://github.com/user-attachments/assets/cf638eec-fbc5-434c-a8a0-35a67070349d)

**Comment by rusty-snake** [comment]
WFM
- SCEE 58.22
- AOSP 14 QPR3
- Gesture Navigation

Related: #613

**Comment by mnalis** [comment]
@rusty-snake interesting, could you share a screenshot (of SCEE-only preference screen, like `UI` in my examples) ?
On my Android 14 there is no arrow in that top bar, neither in buttons nor gesture Android modes.

**Comment by mnalis** [comment]
On Android 14, Xiaomi Redmi Note 13, it is broken in `58.2` and `59.0-alpha2`:
![small_Screenshot_2024-09-06-02-41-37-204_de westnordost streetcomplete expert](https://github.com/user-attachments/assets/81a22cfd-7196-4670-b59a-14b0cf05a426) ![small_Screenshot_2024-09-06-02-35-54-044_de westnordost streetcomplete expert](https://github.com/user-attachments/assets/89ae0448-9622-41b3-8de6-d4ad3761b075)

but works in `58.21` and `58.22` :
![small_Screenshot_2024-09-06-02-46-59-841_de westnordost streetcomplete expert](https://github.com/user-attachments/assets/dd4bca4e-7df1-4215-857e-abca24d5ac47) ![small_Screenshot_2024-09-06-02-36-54-708_de westnordost streetcomplete expert](https://github.com/user-attachments/assets/8cf0f056-0844-4b42-8a2d-96fddb4e71e1)

So I guess it was fixed somewhere in between, but have not made it into `v59.0-alpha2` (and there have  been no further SCEE releases after `alpha2` which include it, and latest SCEE master fails to build so can't test it there easily).

**Comment by mcliquid** [comment]
Relevant PRs:
- https://github.com/Helium314/SCEE/pull/577
- https://github.com/Helium314/SCEE/pull/596

I guess it has been deactivated here: https://github.com/Helium314/SCEE/commit/ec0660e3c856a316a77382e7efd08979bdc8a8d2#diff-de7525ef2b31d51f2f9a717ec1c5ce00795b546dd348b81318d6d5b07e794ab2

**Comment by mnalis** [comment]
> I guess it has been deactivated here: https://github.com/Helium314/SCEE/commit/ec0660e3c856a316a77382e7efd08979bdc8a8d2#diff-de7525ef2b31d51f2f9a717ec1c5ce00795b546dd348b81318d6d5b07e794ab2

Thanks for that research @mcliquid, it seems it is still unfixed in current master 38fce281f69c21cd5ad00c5d71cbfc650aa0ba73 then, so  this issue should remain open:

```
% fgrep -r setUpToolbarTitleAndIcon
fgrep -r setUpToolbarTitleAndIcon
DataManagementSettingsFragment.kt://            setUpToolbarTitleAndIcon(this)
DisplaySettingsFragment.kt://            setUpToolbarTitleAndIcon(this)
QuestsSettingsFragment.kt://            setUpToolbarTitleAndIcon(this)
UiSettingsFragment.kt://            setUpToolbarTitleAndIcon(this)
NoteSettingsFragment.kt://            setUpToolbarTitleAndIcon(this)
```

**Comment by mcliquid** [comment]
@mnalis I have re-added the relevant changes locally and cannot find any issues. The implementation works perfectly for me.
@Helium314 any reasons against these changes?

<img width="348" alt="image" src="https://github.com/user-attachments/assets/1ad67ce8-76d1-47cf-8fbe-127b431d1244">

**Comment by Helium314** [comment]
The main issue is that this feature keeps creating merge conflicts, and I don't want to spend even more time on merging upstream just for an (in my opinion) irrelevant extra.

**Comment by Helium314** [comment]
Also it would only be temporary, until SCEE settings screens are migrated to compose.

**Comment by mnalis** [comment]
It was fixed by PR https://github.com/Helium314/SCEE/pull/668; but see comments in https://github.com/Helium314/SCEE/pull/668#issuecomment-2388913549
