### ISSUE TITLE
New Quest: What kind of caravan site is this? (`caravan_site:type`)

### ISSUE THREAD

**Issue by mcliquid** [Helium314/StreetComplete#641]
### General
Affected tag(s) to be modified/added: [caravan_site:type](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dcaravan_site)
Taginfo: https://taginfo.openstreetmap.org/keys/caravan_site%3Atype#overview
Question asked: **What kind of caravan site is this?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/Helium314/SCEE/blob/modified/QUEST_GUIDELINES.md)):
- [ ] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give should have an equivalent tagging (SCEE quests may not be answerable in all cases, but please keep this rare)
- [x] 🐿️ A survey is necessary (may require knowledge of the subject, though easy answering for everyone is preferred)
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
```
nodes, ways, relations with
  tourism = caravan_site and (
  !caravan_site:type
)
```

**Possible Answers:** 
- village
- river
- lake
- town
- parking_lot
- harbour
- winery
- camp_site
- museum
- restaurant
- farm
- beach
- supermarket

**Proposed UI:**
Similar to outdoor_seating Quest with a simple text selection of values. Probably not possible without images, but a description can, but does not necessarily have to be added.

**Comment by Helium314** [comment]
> Probably not possible without images

Why not? The descriptions in the wiki appear to be clear enough to me.

**Comment by mcliquid** [comment]
> Why not? The descriptions in the wiki appear to be clear enough to me.

Yeah sure, but is there already a Quest Form with just Headline and Description without images?

**Comment by Helium314** [comment]
Not anything with a specific separate headline, but you can still use e.g. "beach: next to a beach". Not sure, but maybe you can also add a line break in the text.

**Comment by goldfndr** [comment]
One more minor edit: "wineyards" should be "vineyards". (I've corrected the wiki page.)
