### ISSUE TITLE
Add Swimming Pool Availability Quest

### ISSUE THREAD

**Issue by mcliquid** [Helium314/StreetComplete#654]
### General
Affected tag(s) to be modified/added: [swimming_pool](https://wiki.openstreetmap.org/wiki/Key:swimming_pool)
Question asked: **Is there a swimming pool here?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/Helium314/SCEE/blob/modified/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give should have an equivalent tagging (SCEE quests may not be answerable in all cases, but please keep this rare)
- [x] 🐿️ A survey is necessary (may require knowledge of the subject, though easy answering for everyone is preferred)
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
```
nodes, ways with
         (
           leisure ~ resort
           or leisure = sports_hall and sport = swimming
           or tourism ~ camp_site|hotel
         )
         and !swimming_pool
```

**Proposed UI:**
Solution A:
- Simple Yes/No Quest, just ask for a `swimming_pool` - easy as toilet availability quest

Solution B:
- Based on OutdoorSeating or SmokingAllowed Quest, ask for `outdoor`, `inground`, `no` and both (`outdoor;inground`).

**Proposed Icon:**
https://wiki.openstreetmap.org/wiki/File:Swimming-16.svg

**Comment by Helium314** [comment]
> * Based on OutdoorSeating or SmokingAllowed Quest, ask for `outdoor`, `inground`, `no` and both (`outdoor;inground`).

I'd rather have `outdoo`, `indoor`, both, `no`. It probably rare that one of these facilities does have a swimming pool that's not `inground`.
