### ISSUE TITLE
Add POI in way menu doesn't load text for list properly 

### ISSUE THREAD

**Issue by RubenKelevra** [Helium314/StreetComplete#656]
Long pressing on a way will give the option to add a POI into the way itself at this position. 

After confirmation of the way, based on its tags you're presented with what looks to be the same menu as the normal POI search list. 

However the recent items only load their icons properly, but the text stays empty and the list also claims that "Nothing [was] found". 

Clicking on one of the broken items with no text does however work. 

**Screenshot**
![Screenshot_2024-09-17-06-46-04-490-edit_de westnordost streetcomplete expert](https://github.com/user-attachments/assets/7ca1b2ae-6587-48d5-8403-d8c5c64bf814)

**How to Reproduce**
- Add POI into way by long clicking on a way on the map
- Confirm way 
- Select a POI from the list by searching 
- Add another POI into way by long clicking on another way on the map
- Confirm way
- observe bug 

**Expected Behavior**
The text should load properly and the list shouldn't display "Nothing found" if nothing was searched for 

**Does it happen in normal StreetComplete?**
SC doesn't have this function 

**Versions affected**
Android 12
SCEE 58.22

**Comment by mcliquid** [comment]
> * Select a POI from the list by searching

What did you enter in the search?

**Comment by RubenKelevra** [comment]
@mcliquid doesn't matter. Just search for anything and used it, to make it appear in the "recently used" list, you see on the screenshot.

I've used bollards and stop signs so far

**Comment by mnalis** [comment]
> Clicking on one of the broken items with no text does however work.
> The text should load properly 

Those icons on the far right are not "regular" search items in the list, those are most-recently-used (or MFU?) shortcuts for popular tags. They are always displayed just with icon without text, and are separate from regular search results. It works like that in `Things overlay` too (or long-press + `Add POI`), so I always considered it a feature, and not a bug, and it was quite useful when considering it in that way :smiley: 

> and the list shouldn't display "Nothing found" if nothing was searched for

Is that a fresh install of SCEE, or have you not used "Insert into way" functionality before?
What should in your opinion be shown in the _"search results"_ list if **nothing** was searched for?

For me, when search box is empty, it shows other most-recently-used-low-priority tags there too (58.2 for this screenshot):

![small_Screenshot_20240917_144543_SCEE](https://github.com/user-attachments/assets/12a7b4f9-e5a2-4774-a708-a9242681e804)

---

**So, to summarize my understanding**: there are **two** most-recently-used-tags lists shown in that SCEE dialog:

- "Popular" list (always shown, regardless whether you have started to type into search box or not) is displayed in bigger icons without text on far right of the screen, and contains only the most **popular**[^1] tags you have recently used
- the other (main / non-popular) list (using left and center of the screen, i.e. most of the screen) shows (with small icon and description text):
    - tags matching what you have started to type in the search box (if you have started to type), ***or***
    - most-recently-used tags that are not found in that first "popular" list (if you have not yet started to type what to search for), ***or***
    - text `Nothing found` if nothing is yet stored in that non-popular MRU list and you have not started to type in search box yet

In your case @RubenKelevra it seems you have any searched for two popular tags (bollards and stop signs), so they only got in the "popular" list (big icons always shown, without text). 

If you instead search for non-popular tag (e.g. for "manhole") it will end in the "other" (i.e. non-popular) list (which is only shown if you have not started to type search term yet).  

As you keep using SCEE, both lists will get more and more populated, but when you uninstall/clear data, they will start from scratch.

Does that explain the situation @RubenKelevra ?

[^1]: I have not researched how that "popularity" is determined, though

**Comment by mnalis** [comment]
Such behaviour is perhaps not obvious, but this is _"Expert Edition"_ after all :smile_cat: 

Perhaps someone should create SCEE usage instructions for several of less-obvious features on the [SCEE wiki](https://wiki.openstreetmap.org/wiki/SCEE) subpage. It would be much appreciated by many, I'm sure!

**Comment by RubenKelevra** [comment]
Ah, yeah that makes sense. Thanks!

I thought you replaced the standard list from SC with an MRU list and moved the icons to the right, but the text is not rendering correctly.

That's the "always staying the same" list in SC:

![Screenshot_2024-09-17-16-39-45-184-edit_de.westnordost.streetcomplete.expert.jpg](https://github.com/user-attachments/assets/fa4f9d11-a602-496a-9fdf-3188c43b5e16)

I think the combination of no round circle behind it and no visual separation between the left search result and the right ribbon style list threw me off. 

Maybe add at least one of them? 🤔

**Comment by mnalis** [comment]
> I think the combination of no round circle behind it

I think it depends whether it is SC icon from quests (nice colored ones with round circle), or one acquired via [id-tagging-schema](https://github.com/openstreetmap/id-tagging-schema/) (black & white, no circle)

> and no visual separation between the left search result and the right ribbon style list

Yes, perhaps a thin vertical line between them would be nice, if there is an easy way to implement it.

**Comment by mnalis** [comment]
@RubenKelevra I've added vertical separator in https://github.com/Helium314/SCEE/pull/658; would you take a look how you like it?

If you want to test Dev build of SCEE it's available at https://github.com/mnalis/StreetComplete/actions/runs/10908602588 (you can use Dev build in parallel with SC and SCEE release builds, without each affecting the other)

**Comment by RubenKelevra** [comment]
@mnalis I think this amount of margin around the ribbons would help to make it look more uniform:

![Screenshot_2024-09-18-01-08-00-892_de westnordost streetcomplete expert debug~2](https://github.com/user-attachments/assets/490bb2fc-f860-4deb-aa78-682becc4b19f)

**Comment by mnalis** [comment]
@RubenKelevra ok, updated pics and debug apk in https://github.com/Helium314/SCEE/pull/658. Looks better?

**Comment by RubenKelevra** [comment]
@mnalis yeah, but I recommend adding a margin on the right as well. Looks a bit odd right now:

![Screenshot_2024-09-18-03-33-20-493-edit_de westnordost streetcomplete expert debug](https://github.com/user-attachments/assets/e61cd934-cf80-4847-a4e6-42860c8f01c6)

**Comment by nobkd** [comment]
Also, what about a gap between the icons? They look kinda cramped (at least those with circle background)

**Comment by RubenKelevra** [comment]
> Also, what about a gap between the icons? They look kinda cramped (at least those with circle background)

I'm fine with that. Looked a tad cramped, but you wanna cramp them there to get enough items in the list. So thats fine for my eyes.

If we do put gaps in between we might wanna scale the icons to 2/3 of the current size, to still put enough up there

**Comment by mnalis** [comment]
Updated pics/apk in https://github.com/Helium314/SCEE/pull/658 to add padding on the right side too.
_Hopefully_ that resolves this specific issue; I understand now why Helium314 hates having to deal with UI design :smiling_face_with_tear: 

For other UI improvements, I'll leave it to other interested parties. PRs welcome! (hey, ***I*** didn't know _anything_ about android layout design before I invested few hours yesterday and today to learn and try to improve this)

**Comment by RubenKelevra** [comment]
Looks perfect, good work! :)
