### ISSUE TITLE
Add crossing:markings=no when adding crossing=unmarked

### ISSUE THREAD

**Issue by meiphoo7-Mae** [Helium314/StreetComplete#674]
**Use case**

I got inspiration for this feature request from #637. FWIW: Even after 5+ years of using SC/SCEE I wasn't aware either about the existence of this extension. But anyway...

I've the habit of tagging a crossing on places where a footway crosses an other type of road and where a crossing either marked or unmarked is obvious or likely. To my surprise after activating this extension I got a lot of new quests about crossing markings, because I didn't know about this tag. This is of course good news for my statistics department....  :-)
Still it got me thinking: if I mark a crossing as being unmarked then I think it would be obvious that the answer on the markings quest would be 'No'.
Also [OSM wiki](https://wiki.openstreetmap.org/wiki/Key:crossing:markings) states: |**crossing:markings** | no |The absence of crossing markings at a crossing. Implied by [crossing](https://wiki.openstreetmap.org/wiki/Key:crossing)=[unmarked](https://wiki.openstreetmap.org/wiki/Tag:crossing%3Dunmarked).

**Proposed Solution**

I would like to propose to automatically add crossing:markings=no when adding crossing=unmarked in the regular crossing quest or follow the wiki and don't ask for markings at all when the user has answered that the crossing is unmarked. Also in the (probably unlikely) situation that an unmarked crossing is later converted to a marked one during road reconstruction that situation should be handled too.

**Comment by Helium314** [comment]
For which quest does SCEE add `crossing=unmarked`?

**Comment by meiphoo7-Mae** [comment]
Sorry, there are no untagged crossings left in the area where I tag and I don't care enough to try to figure this out because there's still a lot of work to do in my area. Maybe I'll revisit it later but for now I'm going to close this.
