### ISSUE TITLE
Overlay node circle icons have a square halo at lower zooms and tilt

### ISSUE THREAD

**Issue by pkoby** [Helium314/StreetComplete#678]
At the lowest zoom that a point overlay is still visible on the map, the icons farthest away have increasingly opaque square halos, visible when the map is tilted. Zooming in slowly makes the halos more transparent until they disappear.

**How to Reproduce**
- Create a custom overlay that looks for points (for instance, I have a tree overlay, colored by `species`).
- Zoom out to the level just before the points are hidden
- Tilt the map
<details>
<summary>Screenshot</summary>

![2024-10-03 17 52 41](https://github.com/user-attachments/assets/5708257a-6dc8-4cef-8900-be087ee46dba)
</details>

**Expected Behavior**
Circles should appear the same as always.

**Does it happen in normal StreetComplete?**
n/a

**Versions affected**
59.2

**Comment by Helium314** [comment]
>Does it happen in normal StreetComplete?
n/a

It _does_ happen in StreetComplete, though obviously not with a custom overlay.

**Comment by pkoby** [comment]
Oh yeah, I guess I didn't consider that the Places or Things overlays were the same, because they're not colored dots. Oops.

**Comment by Helium314** [comment]
Did you report this on SC repo? If not I'll open an issue there and then close this one.

**Comment by pkoby** [comment]
I hadn't. I just did. I can close this.
https://github.com/streetcomplete/StreetComplete/issues/6048
