### ISSUE TITLE
Add sac_scale=strolling to existing quest

### ISSUE THREAD

**Issue by pkoby** [Helium314/StreetComplete#692]
Voting passed the proposal to add `sac_scale=strolling`, so I think it should be added to the existing quest asking for hikability.

There is already a photo on the [wiki page](https://wiki.openstreetmap.org/wiki/Key:sac_scale) that should be usable like the rest. Sorry I don't know how to make this change myself.

**Comment by mcliquid** [comment]
Thanks for the input. I will update the quest next week.

**Comment by goldfndr** [comment]
I'm still hoping to see more of the Trail column's text added to the strings (as mentioned in #557 after merging).

**Comment by mcliquid** [comment]
> I'm still hoping to see more of the Trail column's text added to the strings (as mentioned in #557 after merging).

@goldfndr If you provide me the customized strings, I can implement them together with this change.

**Comment by mnalis** [comment]
(ref: https://wiki.openstreetmap.org/wiki/Proposal:Add_strolling_to_sac_scale_and_some_further_refinements)
