### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by jacklollz2** [Helium314/StreetComplete#698]
The contents of this have been erased.

**Comment by Helium314** [comment]
There already is the possibility to disable it until next app start, that should be enough for the rare cases where the on-site detection fails.

**Comment by mnalis** [comment]
> There already is the possibility to disable it until next app start

Also,  newer Androids (works on my Android 14 on Samsung Galaxy S23+; don't know when it was introduced) allow user to keep the app open so it will not "close" (in app switcher, click on the app icon in the title, then choose `Keep open`).

**Comment by jacklollz2** [comment]
I don't leave this app running in the background using up my battery, just so a pointless notification can go away.

**Comment by Helium314** [comment]
If you don't enable the nearby quest notifications, or the app is currently up/downloading, it shouldn't use battery when in background.
How much battery is it using when just in background?
