### ISSUE TITLE
"syntax error" toast is too persistent (when editing elementFilter)

### ISSUE THREAD

**Issue by mnalis** [Helium314/StreetComplete#701]
When editing `elementFilter` (e.g. overlay selection, or tuning quests), if the syntax is not correct a toast is generated. And  it seems that new toast is generated for every new keypress (as it takes some time until the query is completely written and thus syntax check passes), thus the sequence of toasts remains on a screen for a long time -- even after the form is closed, or even the SCEE app exited!

Related issues:
- point 4 of https://github.com/Helium314/SCEE/discussions/498
- point 3 of https://github.com/Helium314/SCEE/issues/679

<details>
<summary>See the attached video [click to expand]</summary>

https://github.com/user-attachments/assets/2274fbf3-70a1-4b73-a5b2-778ed0080d7e

</details>

**Use case**
The mentioned Android toast in many devices (e.g. on my Android 14) lingers for long even after the elementFilter form is closed and obscures the view. That reduces usability.

**Proposed Solution**
Something which reduces the problem and is easiest to implement:
- only generate toast (or new window?) when user attempts to click `OK` and there is syntax error, or
- replace toast with message at the bottom of the form, or
- _at least_ clear all existing toasts when `OK` button is pressed (least preferred)

**Comment by Helium314** [comment]
> only generate toast (or new window?) when user attempts to click OK and there is syntax error

This would require a lot of customization for the dialog, because the ok button should still show as disabled when the input will not be accepted. But at the same time it should not be actually disabled or it couldn't trigger a toast.

> replace toast with message at the bottom of the form

This would probably look quite awkward, and also changes height of the form. The latter will be very annoying.

> at least clear all existing toasts when OK button is pressed (least preferred)

I don't know how to do this / whether this is possible.

How about starting a timer, and only show a toast if after something like 3 seconds of unchanged text?
Though this will not help against the toasts staying on screen for a few seconds.

**Comment by mnalis** [comment]
> How about starting a timer, and only show a toast if after something like 3 seconds of unchanged text?

I think that might work good enough! Because those 3 seconds:
- should not be too long to wait if one wants to press `OK` but cannot (and is wondering why), and 
- yet it would long enough so previous toast will expire before new one can be triggered.

>  Though this will not help against the toasts staying on screen for a few seconds.

Yeah, but since it will be (at most) **one** toast (instead of easily few dozen queued ones as is currently the case!) that should not be really problematic anymore, I think.

**Comment by Helium314** [comment]
> Yeah, but since it will be (at most) one toast (instead of easily few dozen queued ones as is currently the case!) that should not be really problematic anymore, I think.

That seems to be related to the great idea of things behaving different depending Android version. On my phone the old toast disappears immediately when another one is called.
